###################################################################
#
#      .___          /\ __      __                       .__
#    __| _/____   ___)//  |_  _/  |_  ____  __ __   ____ |  |__
#   / __ |/  _ \ /    \   __\ \   __\/  _ \|  |  \_/ ___\|  |  \
#  / /_/ (  <_> )   |  \  |    |  | (  <_> )  |  /\  \___|   Y  \
#  \____ |\____/|___|  /__|    |__|  \____/|____/  \___  >___|  /
#       \/           \/                                \/     \/
#
###################################################################
#            Make all local changes to httpd-custom.conf
###################################################################

###################################################################
#          THIS IS A THIN COPY, NOT INTENDED FOR PRODUCTION
###################################################################

ServerRoot "/etc/httpd"

# Listen: Allows you to bind Apache to specific IP addresses and/or
# ports, instead of the default. See also the <VirtualHost>
# directive.
#
# Change this to Listen on specific IP addresses as shown below to
# prevent Apache from glomming onto all bound IP addresses.
#
GracefulShutdownTimeout 15

LoadModule deflate_module modules/mod_deflate.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule logio_module modules/mod_logio.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so

LoadModule rewrite_module modules/mod_rewrite.so
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule http2_module         modules/mod_http2.so
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
LoadModule systemd_module modules/mod_systemd.so
LoadModule authz_core_module modules/mod_authz_core.so

# Custom modules will be added by apxs below here and carried over
# between httpd package upgrades. You must leave this "MODULE_MARKER" marker
#
# Only modules loaded with a "LoadModule" directive are carried over.
# Make all module configuration changes to httpd-custom.conf
###########################################################################
# MODULE_MARKER

ExtendedStatus off

User apache
Group apache
Mutex pthread default

# Check for PHP presence
<IfModule php_module>
  Define PHP_INSTALLED
</IfModule>
<IfModule php7_module>
  Define PHP_INSTALLED
</IfModule>
<IfModule php5_module>
  Define PHP_INSTALLED
</IfModule>

DocumentRoot "/var/www/html"

Timeout 30
ServerTokens Prod
KeepAliveTimeout 3
ServerSignature Off
UseCanonicalName off
PidFile run/httpd.pid

<Directory />
  Options PrivilegedSymlinks
  AllowOverride None
</Directory>

HostnameLookups off

EnableSendfile on
EnableMMAP on

<IfModule mpm_worker_module>
  StartServers          5
  MaxClients          250
  MinSpareThreads      25
  MaxSpareThreads      75
  ThreadsPerChild      25
  MaxConnectionsPerChild   128
</IfModule>

<IfModule http2_module>
  Protocols h2 h2c http/1.1
  ProtocolsHonorOrder Off
 </IfModule>

<IfModule brotli_module>
AddOutputFilterByType BROTLI_COMPRESS text/html text/xml text/css text/plain text/javascript application/json application/javascript image/svg+xml
</IfModule>
TraceEnable off

ErrorLog logs/error_log
LogLevel notice

Include conf/httpd-custom.conf
